### ISSUE TITLE
pyproj==1.9.5.* requirement causing installation issues on Mac OSX

### ISSUE THREAD

**Issue by yoninachmany** [azavea/raster-vision#717]
Running `setup.py install` for pyproj fails to build pyproj 1.9.5.* with 15 warnings and 15 errors generated (only works in a virtual environment). Trying to circumvent the problem installing pyproj with Python 3.7 by using `git+https` installs pyproj 2.0.* , which is uninstalled because of the 1.9.5.* requirement. Pip installing in editable mode with a later pyproj version alleviates the build issues.

With the editable/virtualenv installation, I'm having issues with the QGIS plugin finding Raster Vision.

**Comment by lewfish** [comment]
Looks like you were trying to follow these instructions: https://github.com/azavea/raster-vision/blob/e48e527fb8e98e306b338bba43e03d14e1815812/docs/setup.rst#L19-L30

The `master` branch of `pyproj` changed recently to version 2.x. That workaround was documented back when the master branch was on 1.9.5. So I would use 
`pip install git+https://github.com/jswhit/pyproj.git@9ff90a48d90d9e7fa643908c182a91d85c68de79` which is the commit that corresponds to 1.9.5.

Hopefully that works.

**Comment by lewfish** [comment]
Also, as a heads up, the QGIS plugin doesn't work with the `develop` branch of RV. It only works with 0.8, although we're fixing that at the moment. And the examples `master` branch uses features that aren't in 0.8. In the next release all the repos are going to be versioned.

**Comment by yoninachmany** [comment]
Good catch on using a different commit, the installation worked with the [commit right before the 1.9.6 release](https://github.com/jswhit/pyproj/commit/e56e879438f0a1688b89b33228ebda0f0d885c19): `pip install git+https://github.com/jswhit/pyproj.git@e56e879438f0a1688b89b33228ebda0f0d885c19`

Thanks for the heads up. Can the QGIS plugin work with results from the roads/buildings segmentation example as it is now? I've been getting a mix of errors from `ProtobufParseException...You might need to run scripts/compile` to `AttributeError: 'ExperimentDialog' object has no attribute 'experiment'`.

**Comment by lewfish** [comment]
I don't think the latest version of the Vegas example will work with the QGIS plugin. If you go back to an older commit of it from right before the 0.8 release it should work if using RV version 0.8. https://github.com/azavea/raster-vision-examples/commit/efbced2d986bcb99ad442ff3cd3d87bce2278552#diff-5eafa7f8ec9499fe6429daf66c7c66e5
